# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: user/repo

media_folder: /static/media
public_folder: /media

slug:
  encoding: unicode
  clean_accents: false
  sanitize_replacement: '-'
  trim: true
  lowercase: true
  timezone: utc

collections:
  - name: docs
    label: Docs
    folder: /content/docs
    nested:
      depth: 100
      summary: '{{title}}'
      subfolders: false
    meta: { path: { index_file: _index } }
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: posts
    label: Posts
    folder: content/posts
    nested:
      depth: 100
      subfolders: true
    meta: { path: { index_file: _index } }
    path: '{{year}}/{{year}}-{{month}}-{{day}}-{{slug}}/index'
    fields:
      - { name: tags, label: Tags, widget: list, field: { name: tag, label: Tag, widget: string }, required: false }
      - { name: featured, label: Featured, widget: image, required: false }
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: richtext }
  - name: ephemera
    label: Ephemera
    folder: content/ephemera
    path: '{{year}}/{{year}}-{{month}}/{{year}}-{{month}}-{{day}}_{{hour}}-{{minute}}-{{second}}/index'
    fields:
      - { name: body, label: Body, widget: richtext }
